### ISSUE TITLE
CI tests should run automatically on latest release or pre-release of MeiliSearch

### ISSUE THREAD

**Issue by mdubus** [meilisearch/mini-dashboard#184]
For the moment, in tests.yml I have hard-coded the version of MeiliSearch, on which to launch the tests.

```
 services:
      meilisearch:
        image: getmeili/meilisearch:v0.24.0rc2
        env:
          MEILI_MASTER_KEY: 'masterKey'
          MEILI_NO_ANALYTICS: 'true'
        ports:
          - '7700:7700'
```

This means that on every release, or pre-release I have to manually update the version.
We should find a way to automate the version update.
